# pylint: disable=C0301,C0103
# Generated by Django 4.2.16 on 2024-11-29 13:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tcloud", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auditcallback",
            name="creation_time",
            field=models.CharField(blank=True, db_index=True, max_length=32, null=True, verbose_name="Audit Time"),
        ),
    ]
