# pylint: disable=R0801,C0103
# Generated by Django 5.2.9 on 2025-12-15 14:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tcloud", "0002_alter_auditcallback_creation_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auditcallback",
            name="is_sensitive",
            field=models.BooleanField(db_index=True, verbose_name="Is Sensitive"),
        ),
    ]
