# pylint: disable=R0801,C0103
# Generated by Django 4.2 on 2023-04-15 08:59

import ovinc_client.core.models
import ovinc_client.core.utils
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="NoticeLog",
            fields=[
                (
                    "id",
                    ovinc_client.core.models.UniqIDField(
                        default=ovinc_client.core.utils.uniq_id_without_time,
                        max_length=32,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("receivers", models.JSONField(verbose_name="Receivers")),
                ("content", models.JSONField(verbose_name="Content")),
                ("extra_params", models.JSONField(default=dict, null=True, verbose_name="Extra Params")),
                ("result", models.TextField(blank=True, null=True, verbose_name="Result")),
                ("send_at", models.DateTimeField(auto_now_add=True, verbose_name="Send At")),
            ],
            options={
                "verbose_name": "Notice Log",
                "verbose_name_plural": "Notice Log",
                "ordering": ["-send_at"],
            },
        ),
        migrations.CreateModel(
            name="Robot",
            fields=[
                (
                    "id",
                    ovinc_client.core.models.UniqIDField(
                        default=ovinc_client.core.utils.uniq_id_without_time,
                        max_length=32,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("webhook", models.CharField(max_length=255, verbose_name="Webhook")),
                ("name", models.CharField(max_length=32, verbose_name="Name")),
            ],
            options={
                "verbose_name": "Robot",
                "verbose_name_plural": "Robot",
                "ordering": ["id"],
            },
        ),
    ]
