# pylint: disable=R0801,C0103
# Generated by Django 4.2.13 on 2024-07-10 09:44

import ovinc_client.core.models
import ovinc_client.core.utils
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MetaConfig",
            fields=[
                (
                    "id",
                    ovinc_client.core.models.UniqIDField(
                        default=ovinc_client.core.utils.uniq_id_without_time,
                        max_length=32,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(max_length=255, unique=True, verbose_name="Config Key")),
                ("val", models.TextField(blank=True, null=True, verbose_name="Config Value")),
                ("is_public", models.BooleanField(db_index=True, default=True, verbose_name="Is Public")),
            ],
            options={
                "verbose_name": "Meta Config",
                "verbose_name_plural": "Meta Configs",
                "ordering": ["key"],
            },
        ),
    ]
