# pylint: disable=R0801,C0103
# Generated by Django 4.2.3 on 2023-09-11 12:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0002_remove_user_wechat_id_user_wechat_open_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_staff",
            field=models.BooleanField(default=False, verbose_name="Is Staff"),
        ),
    ]
