# pylint: disable=R0801,C0103
# Generated by Django 4.2.3 on 2023-09-15 11:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0003_user_is_staff"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="avatar",
            field=models.TextField(blank=True, null=True, verbose_name="Avatar"),
        ),
        migrations.AlterField(
            model_name="user",
            name="email_address",
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name="Email Address"),
        ),
        migrations.AlterField(
            model_name="user",
            name="phone_number",
            field=models.CharField(blank=True, max_length=32, null=True, unique=True, verbose_name="Phone Number"),
        ),
        migrations.AlterField(
            model_name="user",
            name="wechat_open_id",
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name="Wechat Open ID"),
        ),
        migrations.AlterField(
            model_name="user",
            name="wechat_union_id",
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name="Wechat Union ID"),
        ),
    ]
