# pylint: disable=R0801,C0103
# Generated by Django 4.2.13 on 2024-07-26 09:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0005_usertoken"),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name="usertoken",
            index_together={("user", "session_key", "expired_at"), ("user", "expired_at")},
        ),
    ]
