# pylint: disable=R0801,C0103
# Generated by Django 4.2.13 on 2024-07-26 09:10
from urllib.parse import urlparse

from django.conf import settings
from django.db import migrations
from django.db.models import F, Value
from django.db.models.functions import Concat


def fake_email(*args, **kwargs):
    from apps.account.models import User  # pylint: disable=C0415

    url = urlparse(settings.BACKEND_URL)
    User.objects.filter(email_address__isnull=True).update(
        email_address=Concat(F("username"), Value(f"@{url.hostname}"))
    )


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0006_alter_usertoken_index_together"),
    ]

    operations = [
        migrations.RunPython(fake_email),
    ]
