# pylint: disable=R0801,C0103
# Generated by Django 5.2.9 on 2025-12-15 14:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0007_fake_email"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="usertoken",
            new_name="account_use_user_id_c02769_idx",
            old_fields=("user", "session_key", "expired_at"),
        ),
        migrations.RenameIndex(
            model_name="usertoken",
            new_name="account_use_user_id_d3f0e3_idx",
            old_fields=("user", "expired_at"),
        ),
    ]
