# pylint: disable=R0801,C0103
# Generated by Django 4.2 on 2023-04-15 07:51

import django.db.models.deletion
import ovinc_client.core.models
import ovinc_client.core.utils
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Application",
            fields=[
                ("is_deleted", models.BooleanField(db_index=True, default=False, verbose_name="Soft Delete")),
                ("app_name", models.CharField(max_length=32, verbose_name="App Name")),
                (
                    "app_code",
                    models.CharField(max_length=32, primary_key=True, serialize=False, verbose_name="App Code"),
                ),
                ("app_secret", models.TextField(blank=True, null=True, verbose_name="App Secret (Encoded)")),
                ("app_url", models.URLField(blank=True, null=True, verbose_name="App Url")),
                ("app_logo", models.URLField(blank=True, null=True, verbose_name="App Logo")),
            ],
            options={
                "verbose_name": "Application",
                "verbose_name_plural": "Application",
                "ordering": ["app_code"],
            },
        ),
        migrations.CreateModel(
            name="ApplicationManager",
            fields=[
                (
                    "id",
                    ovinc_client.core.models.UniqIDField(
                        default=ovinc_client.core.utils.uniq_id_without_time,
                        max_length=32,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "application",
                    ovinc_client.core.models.ForeignKey(
                        db_constraint=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="application.application",
                        verbose_name="Application",
                    ),
                ),
                (
                    "manager",
                    ovinc_client.core.models.ForeignKey(
                        db_constraint=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Manager",
                    ),
                ),
            ],
            options={
                "verbose_name": "Application Manager",
                "verbose_name_plural": "Application Manager",
                "ordering": ["id"],
                "unique_together": {("application", "manager")},
            },
        ),
    ]
