# pylint: disable=R0801,C0103
# Generated by Django 4.2 on 2023-04-24 09:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("application", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="application",
            name="app_desc",
            field=models.TextField(blank=True, null=True, verbose_name="App Desc"),
        ),
    ]
