# pylint: disable=C0103
# Generated by Django 4.2.16 on 2024-11-20 12:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("application", "0002_application_app_desc"),
    ]

    operations = [
        migrations.AddField(
            model_name="application",
            name="is_hidden",
            field=models.BooleanField(default=False, verbose_name="Is Hidden"),
        ),
    ]
